{% set data = load_setup_py_data() %}

package:
  name: sklearn-pandas
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - scikit-learn>=1.5.0
    - scipy>=1.5.1
    - pandas>=2.0.0
    - numpy>=2.0.0

  run:
    - python
    - scikit-learn>=1.5.0
    - scipy>=1.5.1
    - pandas>=2.0.0
    - numpy>=2.0.0

test:
  imports:
    - sklearn_pandas

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}

summary: {{ data['description'] }}